#!/usr/bin/env python3
"""Generate synthetic South African ID numbers for test fixtures.

Format: YYMMDD SSSS C A Z
  SSSS  gender sequence (0000-4999 female, 5000-9999 male)
  C     citizenship (0 = SA citizen, 1 = permanent resident)
  A     legacy race digit, now always 8
  Z     Luhn check digit over all 13 digits

The numbers are synthetic and must only be used as test data.
Usage: python specs/generate_sa_ids.py > specs/verified-sa-ids.txt
"""

# (date of birth YYMMDD, gender sequence, citizenship)
SEEDS = [
    ("900101", "5009", "0"),
    ("850615", "0123", "0"),
    ("770312", "5432", "0"),
    ("950228", "0456", "1"),
]


def luhn_valid(number: str) -> bool:
    total = 0
    for position, char in enumerate(reversed(number)):
        digit = int(char)
        if position % 2 == 1:
            digit *= 2
            if digit > 9:
                digit -= 9
        total += digit
    return total % 10 == 0


def with_check_digit(first12: str) -> str:
    return next(first12 + str(d) for d in range(10) if luhn_valid(first12 + str(d)))


if __name__ == "__main__":
    print("# Synthetic SA ID numbers for test fixtures (Luhn-valid, synthetic test data only)")
    print("# Generated by specs/generate_sa_ids.py; do not edit by hand")
    print()
    for dob, sequence, citizenship in SEEDS:
        print(with_check_digit(dob + sequence + citizenship + "8"))
